server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  mongodb:
    database: alioth_db
    host: cloud.jecosine.com
    port: 24680
    username: alioth
    password: ac41f5c6df7a3f12ecd48b74f80e820c

  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

jwt:
  secret: alioth