// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Jecosine/alioth-kratos/internal/biz"
	"github.com/Jecosine/alioth-kratos/internal/conf"
	"github.com/Jecosine/alioth-kratos/internal/data"
	"github.com/Jecosine/alioth-kratos/internal/server/judger"
	"github.com/Jecosine/alioth-kratos/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(server *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	judgerRepo := data.NewJudgerRepo(dataData, logger)
	judgerUsecase := biz.NewJudgerUsecase(judgerRepo, logger)
	judgerService := service.NewJudgerService(judgerUsecase)
	httpServer := judger.NewJudgerHTTPServer(server, judgerService, logger)
	grpcServer := judger.NewJudgerGRPCServer(server, judgerService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
