// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: proto/judger_schemas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JudgeRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User        *UserProto    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	CreatedTime int64         `protobuf:"varint,3,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	SourceCode  string        `protobuf:"bytes,4,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`
	Problem     *ProblemProto `protobuf:"bytes,5,opt,name=problem,proto3" json:"problem,omitempty"`
}

func (x *JudgeRequestProto) Reset() {
	*x = JudgeRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_judger_schemas_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JudgeRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeRequestProto) ProtoMessage() {}

func (x *JudgeRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_judger_schemas_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeRequestProto.ProtoReflect.Descriptor instead.
func (*JudgeRequestProto) Descriptor() ([]byte, []int) {
	return file_proto_judger_schemas_proto_rawDescGZIP(), []int{0}
}

func (x *JudgeRequestProto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JudgeRequestProto) GetUser() *UserProto {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *JudgeRequestProto) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *JudgeRequestProto) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *JudgeRequestProto) GetProblem() *ProblemProto {
	if x != nil {
		return x.Problem
	}
	return nil
}

type JudgeReplyProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User         *UserProto `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	FinishedTime int64      `protobuf:"varint,3,opt,name=finished_time,json=finishedTime,proto3" json:"finished_time,omitempty"`
	TimeCost     int64      `protobuf:"varint,4,opt,name=time_cost,json=timeCost,proto3" json:"time_cost,omitempty"`
	MemoryCost   int64      `protobuf:"varint,5,opt,name=memory_cost,json=memoryCost,proto3" json:"memory_cost,omitempty"`
	Status       int64      `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *JudgeReplyProto) Reset() {
	*x = JudgeReplyProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_judger_schemas_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JudgeReplyProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeReplyProto) ProtoMessage() {}

func (x *JudgeReplyProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_judger_schemas_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeReplyProto.ProtoReflect.Descriptor instead.
func (*JudgeReplyProto) Descriptor() ([]byte, []int) {
	return file_proto_judger_schemas_proto_rawDescGZIP(), []int{1}
}

func (x *JudgeReplyProto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JudgeReplyProto) GetUser() *UserProto {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *JudgeReplyProto) GetFinishedTime() int64 {
	if x != nil {
		return x.FinishedTime
	}
	return 0
}

func (x *JudgeReplyProto) GetTimeCost() int64 {
	if x != nil {
		return x.TimeCost
	}
	return 0
}

func (x *JudgeReplyProto) GetMemoryCost() int64 {
	if x != nil {
		return x.MemoryCost
	}
	return 0
}

func (x *JudgeReplyProto) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_proto_judger_schemas_proto protoreflect.FileDescriptor

var file_proto_judger_schemas_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x5f, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70,
	0x69, 0x1a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8, 0x01, 0x0a, 0x11, 0x4a, 0x75, 0x64,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65,
	0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72,
	0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x62,
	0x6c, 0x65, 0x6d, 0x22, 0xc0, 0x01, 0x0a, 0x0f, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x66,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x65, 0x63, 0x6f, 0x73, 0x69, 0x6e, 0x65, 0x2f, 0x61, 0x6c,
	0x69, 0x6f, 0x74, 0x68, 0x2d, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_judger_schemas_proto_rawDescOnce sync.Once
	file_proto_judger_schemas_proto_rawDescData = file_proto_judger_schemas_proto_rawDesc
)

func file_proto_judger_schemas_proto_rawDescGZIP() []byte {
	file_proto_judger_schemas_proto_rawDescOnce.Do(func() {
		file_proto_judger_schemas_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_judger_schemas_proto_rawDescData)
	})
	return file_proto_judger_schemas_proto_rawDescData
}

var file_proto_judger_schemas_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_judger_schemas_proto_goTypes = []interface{}{
	(*JudgeRequestProto)(nil), // 0: api.JudgeRequestProto
	(*JudgeReplyProto)(nil),   // 1: api.JudgeReplyProto
	(*UserProto)(nil),         // 2: api.UserProto
	(*ProblemProto)(nil),      // 3: api.ProblemProto
}
var file_proto_judger_schemas_proto_depIdxs = []int32{
	2, // 0: api.JudgeRequestProto.user:type_name -> api.UserProto
	3, // 1: api.JudgeRequestProto.problem:type_name -> api.ProblemProto
	2, // 2: api.JudgeReplyProto.user:type_name -> api.UserProto
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_judger_schemas_proto_init() }
func file_proto_judger_schemas_proto_init() {
	if File_proto_judger_schemas_proto != nil {
		return
	}
	file_proto_user_schemas_proto_init()
	file_proto_problem_schemas_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_judger_schemas_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JudgeRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_judger_schemas_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JudgeReplyProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_judger_schemas_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_judger_schemas_proto_goTypes,
		DependencyIndexes: file_proto_judger_schemas_proto_depIdxs,
		MessageInfos:      file_proto_judger_schemas_proto_msgTypes,
	}.Build()
	File_proto_judger_schemas_proto = out.File
	file_proto_judger_schemas_proto_rawDesc = nil
	file_proto_judger_schemas_proto_goTypes = nil
	file_proto_judger_schemas_proto_depIdxs = nil
}
