// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: proto/problem_schemas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TagProto) Reset() {
	*x = TagProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_problem_schemas_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagProto) ProtoMessage() {}

func (x *TagProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_problem_schemas_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagProto.ProtoReflect.Descriptor instead.
func (*TagProto) Descriptor() ([]byte, []int) {
	return file_proto_problem_schemas_proto_rawDescGZIP(), []int{0}
}

func (x *TagProto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProblemProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title   string      `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content string      `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Author  *UserProto  `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Tags    []*TagProto `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *ProblemProto) Reset() {
	*x = ProblemProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_problem_schemas_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProblemProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemProto) ProtoMessage() {}

func (x *ProblemProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_problem_schemas_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemProto.ProtoReflect.Descriptor instead.
func (*ProblemProto) Descriptor() ([]byte, []int) {
	return file_proto_problem_schemas_proto_rawDescGZIP(), []int{1}
}

func (x *ProblemProto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProblemProto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProblemProto) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ProblemProto) GetAuthor() *UserProto {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *ProblemProto) GetTags() []*TagProto {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_proto_problem_schemas_proto protoreflect.FileDescriptor

var file_proto_problem_schemas_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x5f,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61,
	0x70, 0x69, 0x1a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x08,
	0x54, 0x61, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x99, 0x01, 0x0a,
	0x0c, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x0a,
	0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x06, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x67, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x65, 0x63, 0x6f, 0x73, 0x69, 0x6e, 0x65, 0x2f,
	0x61, 0x6c, 0x69, 0x6f, 0x74, 0x68, 0x2d, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_problem_schemas_proto_rawDescOnce sync.Once
	file_proto_problem_schemas_proto_rawDescData = file_proto_problem_schemas_proto_rawDesc
)

func file_proto_problem_schemas_proto_rawDescGZIP() []byte {
	file_proto_problem_schemas_proto_rawDescOnce.Do(func() {
		file_proto_problem_schemas_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_problem_schemas_proto_rawDescData)
	})
	return file_proto_problem_schemas_proto_rawDescData
}

var file_proto_problem_schemas_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_problem_schemas_proto_goTypes = []interface{}{
	(*TagProto)(nil),     // 0: api.TagProto
	(*ProblemProto)(nil), // 1: api.ProblemProto
	(*UserProto)(nil),    // 2: api.UserProto
}
var file_proto_problem_schemas_proto_depIdxs = []int32{
	2, // 0: api.ProblemProto.author:type_name -> api.UserProto
	0, // 1: api.ProblemProto.tags:type_name -> api.TagProto
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_problem_schemas_proto_init() }
func file_proto_problem_schemas_proto_init() {
	if File_proto_problem_schemas_proto != nil {
		return
	}
	file_proto_user_schemas_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_problem_schemas_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_problem_schemas_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProblemProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_problem_schemas_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_problem_schemas_proto_goTypes,
		DependencyIndexes: file_proto_problem_schemas_proto_depIdxs,
		MessageInfos:      file_proto_problem_schemas_proto_msgTypes,
	}.Build()
	File_proto_problem_schemas_proto = out.File
	file_proto_problem_schemas_proto_rawDesc = nil
	file_proto_problem_schemas_proto_goTypes = nil
	file_proto_problem_schemas_proto_depIdxs = nil
}
