// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jecosine/alioth-kratos/app/data_service/ent/judgerecord"
	"github.com/Jecosine/alioth-kratos/app/data_service/ent/predicate"
)

// JudgeRecordDelete is the builder for deleting a JudgeRecord entity.
type JudgeRecordDelete struct {
	config
	hooks    []Hook
	mutation *JudgeRecordMutation
}

// Where appends a list predicates to the JudgeRecordDelete builder.
func (jrd *JudgeRecordDelete) Where(ps ...predicate.JudgeRecord) *JudgeRecordDelete {
	jrd.mutation.Where(ps...)
	return jrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (jrd *JudgeRecordDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(jrd.hooks) == 0 {
		affected, err = jrd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*JudgeRecordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			jrd.mutation = mutation
			affected, err = jrd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(jrd.hooks) - 1; i >= 0; i-- {
			if jrd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = jrd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, jrd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (jrd *JudgeRecordDelete) ExecX(ctx context.Context) int {
	n, err := jrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (jrd *JudgeRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: judgerecord.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: judgerecord.FieldID,
			},
		},
	}
	if ps := jrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, jrd.driver, _spec)
}

// JudgeRecordDeleteOne is the builder for deleting a single JudgeRecord entity.
type JudgeRecordDeleteOne struct {
	jrd *JudgeRecordDelete
}

// Exec executes the deletion query.
func (jrdo *JudgeRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := jrdo.jrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{judgerecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (jrdo *JudgeRecordDeleteOne) ExecX(ctx context.Context) {
	jrdo.jrd.ExecX(ctx)
}
