// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Jecosine/alioth-kratos/app/judger/internal/biz"
	"github.com/Jecosine/alioth-kratos/app/judger/internal/conf"
	"github.com/Jecosine/alioth-kratos/app/judger/internal/data"
	"github.com/Jecosine/alioth-kratos/app/judger/internal/server"
	"github.com/Jecosine/alioth-kratos/app/judger/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	judgerRepo := data.NewJudgerRepo(dataData, logger)
	judgerUsecase := biz.NewJudgerUsecase(judgerRepo, logger)
	judgerService := service.NewJudgerService(judgerUsecase)
	httpServer := server.NewHTTPServer(confServer, judgerService, logger)
	grpcServer := server.NewGRPCServer(confServer, judgerService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
