package common

var (
	// JUDGE_STATUS_RUNNING | JUDGE_STATUS_STOP | JUDGE_STATUS_EMPTY stands for judger status
	JUDGE_STATUS_RUNNING int64 = 0
	JUDGE_STATUS_STOP    int64 = 1
	JUDGE_STATUS_EMPTY   int64 = 2
)
