// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Jecosine/alioth-kratos/app/data_service/internal/biz"
	"github.com/Jecosine/alioth-kratos/app/data_service/internal/conf"
	"github.com/Jecosine/alioth-kratos/app/data_service/internal/data"
	"github.com/Jecosine/alioth-kratos/app/data_service/internal/server"
	"github.com/Jecosine/alioth-kratos/app/data_service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, jwt *conf.Jwt, logger log.Logger) (*kratos.App, func(), error) {
	database := data.NewMongoDB(confData, logger)
	dataData, cleanup, err := data.NewData(database, logger)
	if err != nil {
		return nil, nil, err
	}
	authRepo := data.NewAuthRepo(dataData, logger)
	authUsecase := biz.NewAuthUsecase(authRepo, logger)
	authService := service.NewAuthService(authUsecase)
	baseService := service.NewBaseService()
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	httpServer := server.NewHTTPServer(confServer, jwt, authService, baseService, greeterService, logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
